---
# See https://docs.python.org/3/library/logging.config.html#configuration-dictionary-schema
logging:
  version: 1
  disable_existing_loggers: true
  root:
    # Configuring the default (root) logger is highly recommended
    level: DEBUG
    handlers: [console]
    formatter: coloredFormatter
  # loggers:
    # main:
      # handlers: [console]
      # qualname: main
      # propagate: false
      # formatter: coloredFormatter
      # level: DEBUG
  handlers:
    # logfile:
      # class: logging.FileHandler
      # filename: sample.log
      # formatter: simpleFormatter
      # # level: DEBUG
    console:
      class: logging.StreamHandler
      stream: ext://sys.stdout
      formatter: coloredFormatter
      level: DEBUG
  formatters:
    simpleFormatter:
      format: "%(asctime)s,%(msecs)03d %(levelname)s %(name)s:%(funcName)s:%(lineno)s -- %(message)s"
    coloredFormatter:
      (): "coloredlogs.ColoredFormatter"
      datefmt: "%H:%M:%S"
      format: "%(asctime)s,%(msecs)03d %(levelname)s %(name)s:%(funcName)s:%(lineno)s -- %(message)s"
